#  Link2Telegram v1.1.3-pre
#  Created by Crystal-Moling
#  GitHub page:https://github.com/Crystal-Moling/link2telegram

# BotToken obtained from @BotFather
BotToken: '123456:qwertyuiopASDFGHJKL'
# Send information to this chatId
SendMsgToChatID: 1234567890
Proxy:
  #Proxy server address, if not filled, no proxy will be used
  Hostname: '127.0.0.1'
  # proxy server port
  Port: 7890

# Plugin function
ServerStart/StopMessage:
  # Whether to enable Server Start Message
  Enabled: true
  # The message sent when the server starts
  PluginOnEnableMsg: 'Server started'
  # The message sent when the server shuts down
  PluginOnDisableMsg: 'Server down'
TPSMonitor:
  # Whether to enable TPS monitor
  Enabled: true
  # TPS monitoring interval, in seconds
  TPSCheckTimeout: 5
  # TPS max threshold
  MaxTPSThreshold: 22
  # TPS high warning message
  TPSTooHighInformation: 'TPS is too high, current TPS:%TPS%'
  # TPS minimum threshold
  MinTPSThreshold: 18
  # TPS low warning message
  TPSTooLowInformation: 'TPS is too low, current TPS:%TPS%'
PlayerLogin:
  # Whether to enable Player login Listener
  Enabled: true
  # Player Login Message
  PlayerLoginMessage: 'Player %player% login!'