#  Link2Telegram v1.3-fix
#  Created by Crystal-Moling
#  GitHub page:https://github.com/Crystal-Moling/link2telegram

# BotToken obtained from @BotFather
BotToken: '123456:qwertyuiopASDFGHJKL'
# Send information to this chatId
OwnerChatId: 1234567890
SendMsgToChatID:
  - 1234567890
  - 0987654321
Proxy:
  #Proxy server address, if not filled, no proxy will be used
  Hostname: '127.0.0.1'
  # proxy server port
  Port: 7890

# Plugin function
ServerStart/StopMessage:
  # Whether to enable Server Start Message
  Enabled: true
TPSMonitor:
  # Whether to enable TPS monitor
  Enabled: true
  # TPS monitoring interval, in seconds
  TPSCheckTimeout: 5
  # TPS max threshold
  MaxTPSThreshold: 22
  # TPS minimum threshold
  MinTPSThreshold: 18
PlayerLogin:
  # Whether to enable Player login Listener
  Enabled: true

# Plugin Messages
Messages:
  # Server starts message
  PluginOnEnableMsg: 'Server started'
  # Server shuts down message
  PluginOnDisableMsg: 'Server down'
  # TPS high warning message
  TPSTooHighMsg: 'TPS is too high, current TPS:%TPS%'
  # TPS low warning message
  TPSTooLowMsg: 'TPS is too low, current TPS:%TPS%'
  # Player Login Message
  PlayerLoginMsg: 'Player %player% login!'
