#  Link2Telegram v1.0
#  Created by Crystal-Moling
#  GitHub page:https://github.com/Crystal-Moling/link2telegram
BotToken: '123456789:qwertyuiopASDFGHJKL'
SendMsgToChatID: 1234567890
Proxy:
  Hostname: 127.0.0.1
  Port: 7890
DefaultMsg:
  PluginOnEnableMsg: '服务器启动'
  PluginOnDisableMsg: '服务器关闭'

# Plugin functions
TPSMonitor:
  Enabled: true
  # Timeout unit: seconds
  TPSCheckTimeout: 5
  # High TPS monitoring
  MaxTPSThreshold: 22
  TPSTooHighInformation: 'TPS过高,当前TPS:'
  # Whether to add the current TPS after the warning message
  THIEndedWithTPS: true
  # Low TPS monitoring
  MinTPSThreshold: 18
  TPSTooLowInformation: 'TPS过低,当前TPS:'
  # Whether to add the current TPS after the warning message
  TLIEndedWithTPS: true