#  Link2Telegram v1.3.1
#  Created by Crystal-Moling
#  GitHub page:https://github.com/Crystal-Moling/link2telegram

# BotToken obtained from @BotFather
BotToken: '123456:qwertyuiopASDFGHJKL'
# Chat ID of this server owner
OwnerChatId: 1234567890
# Send message to other chats,groups or channels
# - When you need to send message to channel you should use like "@ChannelName"
# - but the "@" couldn't write in config so use "AT:" to show that this is an "@"
# - You needn't write owner's chat id here again
SendMsgToChatID:
  - 987654321
  - 'AT:Channel-name'
Proxy:
  #Proxy server address, if not filled, no proxy will be used
  Hostname: '127.0.0.1'
  # proxy server port
  Port: 7890

# Plugin function
ServerStart/StopMessage:
  # Whether to enable Server Start Message
  Enabled: true
TPSMonitor:
  # Whether to enable TPS monitor
  Enabled: true
  # TPS monitoring interval, in seconds
  TPSCheckTimeout: 5
  # TPS max threshold
  MaxTPSThreshold: 22
  # TPS minimum threshold
  MinTPSThreshold: 18
PlayerLoginLogout:
  # Whether to enable Player login/logout Listener
  Enabled: true

# Plugin Messages
Messages:
  # Server starts message
  PluginOnEnableMsg: 'Server started'
  # Server shuts down message
  PluginOnDisableMsg: 'Server down'
  # TPS high warning message
  TPSTooHighMsg: 'TPS is too high, current TPS:%TPS%'
  # TPS low warning message
  TPSTooLowMsg: 'TPS is too low, current TPS:%TPS%'
  # Player Login Message
  PlayerLoginMsg: 'Player %player% login!'
  # Player Logout Message
  PlayerLogoutMsg: 'Player %player% logout!'
  # Not owner message
  NotOwnerCommand: 'You do not have owner permission!'
