name: Link2telegram
version: '${project.version}'
main: org.crystal.link2telegram.Link2telegram
api-version: 1.18
commands:
  l2treload:
    description: Reload Bot Configuration
  l2treinit:
    description: Reinitialize Telegram Bot
